# Generated by Django 3.2.4 on 2021-07-09 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLoginInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('roll_number', models.CharField(max_length=9)),
                ('department', models.CharField(default='null', max_length=100)),
                ('program', models.CharField(default='null', max_length=50)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(default='null', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('uni', models.CharField(max_length=122)),
                ('is_generated', models.BooleanField(default=False)),
                ('years_taught', models.CharField(max_length=2)),
                ('presentation', models.CharField(max_length=15)),
                ('quality1', models.CharField(max_length=20)),
                ('quality2', models.CharField(max_length=20)),
                ('eca', models.BooleanField(default=False)),
                ('project', models.CharField(max_length=100)),
                ('paper', models.BooleanField(default=False)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.teacherinfo')),
                ('std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.studentlogininfo')),
            ],
        ),
    ]
