# Generated by Django 3.2.3 on 2021-08-19 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLoginInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=120, null=True)),
                ('roll_number', models.CharField(blank=True, max_length=9, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('program', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(blank=True, default='null', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('images', models.ImageField(blank=True, default='cute_baby.gif', upload_to='images/')),
                ('subjects', models.ManyToManyField(to='home.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=122, null=True)),
                ('uni', models.CharField(blank=True, max_length=122, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_generated', models.BooleanField(default=False)),
                ('years_taught', models.CharField(blank=True, max_length=10, null=True)),
                ('gpa', models.CharField(default='null', max_length=5)),
                ('is_pro', models.CharField(default='null', max_length=3)),
                ('final_project', models.CharField(max_length=100)),
                ('project1', models.CharField(default='null', max_length=100)),
                ('paper', models.CharField(default='null', max_length=3)),
                ('paper_title', models.CharField(default='null', max_length=50)),
                ('paper_link', models.CharField(default='null', max_length=200)),
                ('subjects', models.CharField(blank=True, max_length=500, null=True)),
                ('presentation', models.CharField(blank=True, max_length=50, null=True)),
                ('extracirricular', models.CharField(blank=True, max_length=50, null=True)),
                ('academics', models.CharField(blank=True, max_length=50, null=True)),
                ('quality', models.CharField(blank=True, max_length=50, null=True)),
                ('leadership', models.BooleanField(default=False)),
                ('hardworking', models.BooleanField(default=False)),
                ('social', models.BooleanField(default=False)),
                ('teamwork', models.BooleanField(default=False)),
                ('friendly', models.BooleanField(default=False)),
                ('deployed', models.BooleanField(default=False)),
                ('intern', models.BooleanField(default=False)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.teacherinfo')),
                ('std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.studentlogininfo')),
            ],
        ),
    ]
