# Generated by Django 3.2.3 on 2021-08-09 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLoginInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('roll_number', models.CharField(max_length=9)),
                ('department', models.CharField(default='null', max_length=100)),
                ('program', models.CharField(default='null', max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(default='null', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(default='null', max_length=100)),
                ('images', models.ImageField(blank=True, default='cute_baby.gif', upload_to='images/')),
                ('subject1', models.CharField(default='null', max_length=100)),
                ('subject2', models.CharField(default='null', max_length=100)),
                ('subject3', models.CharField(default='null', max_length=100)),
                ('subject4', models.CharField(default='null', max_length=100)),
                ('subject5', models.CharField(default='null', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('uni', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('is_generated', models.BooleanField(default=False)),
                ('years_taught', models.CharField(max_length=2)),
                ('final_project', models.CharField(max_length=100)),
                ('project1', models.CharField(default='null', max_length=100)),
                ('project2', models.CharField(default='null', max_length=100)),
                ('paper', models.BooleanField(default=False)),
                ('paper_link', models.CharField(default='null', max_length=200)),
                ('presentation', models.CharField(max_length=15)),
                ('quality1', models.CharField(max_length=20)),
                ('quality2', models.CharField(max_length=20)),
                ('quality3', models.CharField(max_length=20)),
                ('quality4', models.CharField(max_length=20)),
                ('eca', models.CharField(max_length=3)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.teacherinfo')),
                ('std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.studentlogininfo')),
            ],
        ),
    ]
