# Generated by Django 3.2.4 on 2021-07-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='eca',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='paper',
            field=models.CharField(max_length=3),
        ),
    ]
