# Generated by Django 3.2.3 on 2021-08-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='gpa',
            field=models.CharField(default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='is_pro',
            field=models.CharField(default='null', max_length=3),
        ),
    ]
