# Generated by Django 3.2.3 on 2021-08-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210809_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='paper',
            field=models.CharField(default='null', max_length=3),
        ),
    ]
