# Generated by Django 3.2.3 on 2021-06-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210609_2150'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentLogin',
            new_name='StudentLoginInfo',
        ),
    ]
