# Generated by Django 3.2.3 on 2021-06-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_studentlogin_studentlogininfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('gpa', models.CharField(max_length=12)),
                ('uni', models.CharField(max_length=122)),
                ('professor', models.CharField(max_length=122)),
            ],
        ),
    ]
