# Generated by Django 3.1 on 2021-08-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_studentdata_paper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacherinfo',
            name='subject1',
        ),
        migrations.RemoveField(
            model_name='teacherinfo',
            name='subject2',
        ),
        migrations.RemoveField(
            model_name='teacherinfo',
            name='subject3',
        ),
        migrations.RemoveField(
            model_name='teacherinfo',
            name='subject4',
        ),
        migrations.RemoveField(
            model_name='teacherinfo',
            name='subject5',
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentlogininfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='subjects',
            field=models.ManyToManyField(to='home.Subject'),
        ),
    ]
