# Generated by Django 3.2.3 on 2021-06-22 16:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_studentdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='stime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
