# Generated by Django 3.1 on 2021-08-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210809_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='subjects',
        ),
        migrations.AddField(
            model_name='subject',
            name='s_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
