# Generated by Django 3.1 on 2021-08-09 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210809_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='s_name',
            new_name='name',
        ),
    ]
