# Generated by Django 3.2.3 on 2021-06-22 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_studentdata_stime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdata',
            name='stime',
        ),
    ]
