# Generated by Django 3.1 on 2021-08-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210809_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='subjects',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
