# Generated by Django 3.1 on 2021-07-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210729_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinfo',
            name='images',
            field=models.ImageField(blank=True, default='cute_baby.gif', upload_to='images/'),
        ),
    ]
