# Generated by Django 3.1 on 2021-08-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_studentdata_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='years_taught',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
