# Generated by Django 3.2.3 on 2021-07-01 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_teacherinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.teacherinfo'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
