# Generated by Django 3.2.4 on 2021-08-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210815_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='paper_link',
            field=models.CharField(blank=True, default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='project1',
            field=models.CharField(blank=True, default='null', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='project2',
            field=models.CharField(blank=True, default='null', max_length=100, null=True),
        ),
    ]
