# Generated by Django 3.1 on 2021-08-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210815_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='academics',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='extracirricular',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='paper_link',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='presentation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='project1',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='project2',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='quality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentlogininfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
