# Generated by Django 3.2.4 on 2021-08-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210818_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='years_taught',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
